#!/usr/bin/env bash
server {
listen 80;
server_name simoboukar.tech;

location /airbnb-onepage/ {
proxy_pass http://localhost:5000;
include /etc/nginx/proxy_params;
proxy_redirect off;
}
location /number_odd_or_even/ {
proxy_pass http://localhost:5001;
include /etc/nginx/proxy_params;
proxy_redirect off;
}

location /airbnb-dynamic/number_odd_or_even/ {
proxy_pass http://localhost:5001/number_odd_or_even/;
include /etc/nginx/proxy_params;
proxy_redirect off;
}

location /api/ {
proxy_pass http://localhost:5002;
include /etc/nginx/proxy_params;
proxy_redirect off;
}

location / {
proxy_pass http://localhost:5003/2-hbnb;
include /etc/nginx/proxy_params;
proxy_redirect off;
}
location /static/ {
proxy_pass http://localhost:5003;

# alias /home/ubuntu/AirBnB_clone_v4/web_dynamic/static/;
}
}
